title: "Your Name"
description: "Short description — researcher / developer / writer"
baseurl: ""          # leave empty for user site
url: "https://h-matthias2025.github.io"
markdown: kramdown

# Jekyll defaults
collections: {}
plugins: []

# defaults to apply post layout automatically
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"