title: Matthias
description: Personal research blog
url: https://yourusername.github.io
baseurl: ""

remote_theme: fongandrew/hydeout

author: Matthias

sidebar_home_link: true

paginate: 5
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown

social_links:
  github: yourgithub
  twitter: yourtwitter
  rss: rss
