title: Matthias
description: Personal research blog
url: https://yourusername.github.io
baseurl: ""

theme: hydeout

author:
  name: JMatthias
  email: ""

sidebar_home_link: true

paginate: 5
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

social_links:
  github: yourgithub
  twitter: yourtwitter
  rss: rss

google_analytics: ""
